# Generated by Django 4.1.6 on 2023-02-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_slug_alter_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='slug',
            field=models.SlugField(default='-', unique=True),
        ),
    ]
