# Generated by Django 4.1.6 on 2023-02-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
