# Generated by Django 4.1.6 on 2023-02-08 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_department_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('speciality', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='doctors/default.jpg', upload_to='doctors/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(default='-', max_length=255, unique=True)),
                ('skill', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='doctors.department')),
            ],
        ),
    ]
