# Generated by Django 4.1.6 on 2023-02-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
