# Generated by Django 4.1.6 on 2023-02-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_schedule_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(default='d', max_length=30),
            preserve_default=False,
        ),
    ]
