# Generated by Django 4.1.6 on 2023-02-10 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_alter_doctor_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('job_position', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='doctors.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('starting_date', models.DateField()),
                ('complete_date', models.DateField()),
                ('degree', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=50)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='doctors.doctor')),
            ],
        ),
    ]
