# Generated by Django 4.1.6 on 2023-02-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
    ]
