# Generated by Django 4.1.6 on 2023-02-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_schedule_is_busy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='is_busy',
        ),
    ]
